my.app.title=HELLO CONFIG SERVER

#Provide eureka location
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Generating Instance ID
eureka.instance.instance-id=${spring.application.name}:${random.value}




#Active Actuator
management.endpoints.web.exposure.include=*

#Connect with Admin Server
spring.boot.admin.client.url=http://localhost:9999
